const images = {
    IC_APP: require("../images/logo.svg"),
    IC_APP_BOTTOM: require("../images/logobottom.svg"),
    IC_FB: require("../images/ic_facebook.svg"), 
    IC_INST: require("../images/ic_insta.svg"), 
    IC_LINKEDIN: require("../images/ic_linkedin.svg"), 
    LOGO_TRUSTPILOT: require("../images/logo_trustpilot.png"),
    IMG_RIGHT_ARROW: require("../images/right_arrow.png"),
    BG_HOME: require("../images/bg_home.jpg"),
    BG_WHYUS: require("../images/bg_whyus.jpg"),
    BG_DEST: require("../images/bg_dest.jpg"),
    IMG_HOME_TH_1: require("../images/gallery/img_home_th1.jpg"),
    IMG_HOME_TH_2: require("../images/gallery/img_home_th2.jpg"),
    IMG_HOME_TH_3: require("../images/gallery/img_home_th3.jpg"),
    IMG_HOME_TH_4: require("../images/gallery/img_home_th4.jpg"),
    IMG_HOME_TH_5: require("../images/gallery/img_home_th5.jpg"),
    IMG_HOME_TH_6: require("../images/gallery/img_home_th6.jpg"),
    IMG_HOME_TH_7: require("../images/gallery/img_home_th7.jpg"),
    IMG_HOME_TH_8: require("../images/gallery/img_home_th8.jpg"),
    IMG_HOME_TH_9: require("../images/gallery/img_home_th9.jpg"),
    IMG_HOME_TH_10: require("../images/gallery/img_home_th10.jpg"),
    IMG_HOME_TH_11: require("../images/gallery/img_home_th11.jpg"),
    IMG_HOME_TH_12: require("../images/gallery/img_home_th12.jpg"),
    IC_AIRPLANE: require("../images/ic_airplane.svg"),
    IC_BOAT: require("../images/ic_boat.svg"),
    IC_COMPASS: require("../images/ic_compass.svg"),
    IC_MOUNTAIN: require("../images/ic_mountain.svg"),
    IC_SUITCASE: require("../images/ic_suitcase.svg"),
    IC_VAN: require("../images/ic_van.svg"),
    IC_SIGNPOST: require("../images/ic_signpost.svg"),
    IC_WATCH: require("../images/ic_watch.svg"),
};

export default images;